# Generated by Django 4.0.6 on 2022-08-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(default=' ')),
                ('img', models.ImageField(upload_to='post_image/')),
                ('created', models.DateTimeField()),
            ],
        ),
    ]
