# Generated by Django 4.0.6 on 2022-08-07 13:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0006_alter_post_created_alter_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 7, 13, 24, 48, 36946, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default='post_img/defuatl.png', upload_to='post_image/'),
        ),
    ]
