# Generated by Django 4.0.6 on 2022-08-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0010_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default='post_img/defuatl.png', upload_to='media/post_image/'),
        ),
    ]
