# Generated by Django 4.0.6 on 2022-08-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0014_alter_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default='post_image/', upload_to='post_image/'),
        ),
    ]
